"""add user preferences

Revision ID: abf5d2326800
Revises: eeed2fb27e91
Create Date: 2025-12-25 09:34:27.369841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abf5d2326800'
down_revision = 'eeed2fb27e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_time_window', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
